### ISSUE TITLE
show-stats-table program doesn't run but other user's result is displayed

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/freesurfer-analysis#9]
# Credits
First discovered by @eknyazhe
Diagnosed by @tashrifbillah 

# Description

Although `OSError` is thrown, the program goes to next [line](https://github.com/pnlbwh/freesurfer-analysis/blob/exog-effect/scripts/generate-summary.py#L97) and displays other people's results:

```bash
Traceback (most recent call last):
  File "/home/tb571/Downloads/freesurfer-analysis/scripts/show-stats-table.py", line 133, in <module>
    app.run_server(debug=False, port= table_port, host= 'localhost')
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/dash/dash.py", line 1973, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/home/tb571/miniconda3/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/home/tb571/miniconda3/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/tb571/miniconda3/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use


Displaying table at http://localhost:8052
```

# Idea

Check validity of ports at the beginning of each executable.

```python
import socket
s= socket.socket()
s.connect(PORT_NAME)
```

**Comment by tashrifbillah** [comment]
Should be fixed in PR #10
